[package]
name = "voxels-sdl"
version = "0.1.0"
authors = ["Jacob Lifshay <programmerjake@gmail.com>"]

[lib]
crate-type = ["rlib"]

[build-dependencies]
bindgen = "0.29.1"
pkg-config = "0.3.12"

[dependencies]
libc = "0.2"

[features]
default = []
weak_main = []
no_main = []
