[package]
name = "voxels-base"
version = "0.1.0"
authors = ["Jacob Lifshay <programmerjake@gmail.com>"]

[lib]
crate-type = ["rlib"]

[dependencies]
voxels-image = { path = "../voxels-image" }
voxels-renderer = { path = "../voxels-renderer" }
voxels-math = { path = "../voxels-math" }
